CREATE TABLE Car_Names (
  ID INT NOT NULL,
  Model VARCHAR(25) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  Descr VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 121,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

ALTER TABLE Car_Names 
  ADD CONSTRAINT Car_Names_model_fk FOREIGN KEY (Model)
    REFERENCES Model_Details(Model);