CREATE TABLE Car_Details (
  ID INT NOT NULL,
  mpg FLOAT(5, 2) DEFAULT NULL,
  cylinders INT DEFAULT NULL,
  edispl INT DEFAULT NULL,
  horsepower INT DEFAULT NULL,
  weight INT DEFAULT NULL,
  accel FLOAT(10, 2) DEFAULT NULL,
  year INT DEFAULT NULL,
  horsePower2 INT DEFAULT NULL,
  color VARCHAR(25) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 121,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

ALTER TABLE Car_Details 
  ADD CONSTRAINT Car_Details_id_fk FOREIGN KEY (ID)
    REFERENCES Car_Names(ID);