GRANT DELETE ON xdb.xdb$d_link TO "SYSTEM" WITH GRANT OPTION;
GRANT INSERT ON xdb.xdb$d_link TO "SYSTEM" WITH GRANT OPTION;
GRANT SELECT ON xdb.xdb$d_link TO "SYSTEM" WITH GRANT OPTION;
GRANT UPDATE ON xdb.xdb$d_link TO "SYSTEM" WITH GRANT OPTION;