GRANT DELETE ON xdb.xdb$resconfig TO "SYSTEM" WITH GRANT OPTION;
GRANT INSERT ON xdb.xdb$resconfig TO "SYSTEM" WITH GRANT OPTION;
GRANT SELECT ON xdb.xdb$resconfig TO "SYSTEM" WITH GRANT OPTION;
GRANT UPDATE ON xdb.xdb$resconfig TO "SYSTEM" WITH GRANT OPTION;