GRANT DELETE ON xdb.xdb$nlocks TO "SYSTEM" WITH GRANT OPTION;
GRANT INSERT ON xdb.xdb$nlocks TO "SYSTEM" WITH GRANT OPTION;
GRANT SELECT ON xdb.xdb$nlocks TO "SYSTEM" WITH GRANT OPTION;
GRANT UPDATE ON xdb.xdb$nlocks TO "SYSTEM" WITH GRANT OPTION;