CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM".product_privs (product,userid,"ATTRIBUTE","SCOPE",numeric_value,char_value,date_value,long_value) AS
SELECT PRODUCT, USERID, ATTRIBUTE, SCOPE,
         NUMERIC_VALUE, CHAR_VALUE, DATE_VALUE, LONG_VALUE
  FROM SQLPLUS_PRODUCT_PROFILE
  WHERE USERID = 'PUBLIC' OR USER LIKE USERID;