CREATE TABLE "SYSTEM".logmnr_session$ (
  session# NUMBER NOT NULL,
  client# NUMBER,
  session_name VARCHAR2(128 BYTE) NOT NULL,
  db_id NUMBER,
  resetlogs_change# NUMBER,
  session_attr NUMBER,
  session_attr_verbose VARCHAR2(400 BYTE),
  start_scn NUMBER,
  end_scn NUMBER,
  spill_scn NUMBER,
  spill_time DATE,
  oldest_scn NUMBER,
  resume_scn NUMBER,
  global_db_name VARCHAR2(384 BYTE) DEFAULT null,
  reset_timestamp NUMBER,
  branch_scn NUMBER,
  "VERSION" VARCHAR2(64 BYTE),
  redo_compat VARCHAR2(20 BYTE),
  spare1 NUMBER,
  spare2 NUMBER,
  spare3 NUMBER,
  spare4 NUMBER,
  spare5 NUMBER,
  spare6 DATE,
  spare7 VARCHAR2(1000 BYTE),
  spare8 VARCHAR2(1000 BYTE),
  CONSTRAINT logmnr_session_pk PRIMARY KEY (session#),
  CONSTRAINT logmnr_session_uk1 UNIQUE (session_name)
);