CREATE TABLE "SYSTEM".logmnr_partobj$ (
  parttype NUMBER,
  partcnt NUMBER,
  partkeycols NUMBER,
  flags NUMBER,
  defts# NUMBER,
  defpctfree NUMBER,
  defpctused NUMBER,
  defpctthres NUMBER,
  definitrans NUMBER,
  defmaxtrans NUMBER,
  deftiniexts NUMBER,
  defextsize NUMBER,
  defminexts NUMBER,
  defmaxexts NUMBER,
  defextpct NUMBER,
  deflists NUMBER,
  defgroups NUMBER,
  deflogging NUMBER,
  spare1 NUMBER,
  spare2 NUMBER,
  spare3 NUMBER,
  definclcol NUMBER,
  "PARAMETERS" VARCHAR2(3000 BYTE),
  obj# NUMBER NOT NULL,
  logmnr_uid NUMBER(22),
  logmnr_flags NUMBER(22),
  CONSTRAINT logmnr_partobj$_pk PRIMARY KEY (logmnr_uid,obj#) DISABLE NOVALIDATE
);