CREATE TABLE "SYSTEM".logmnrggc_gtlo (
  logmnr_uid NUMBER NOT NULL,
  keyobj# NUMBER NOT NULL,
  lvlcnt NUMBER NOT NULL,
  baseobj# NUMBER NOT NULL,
  baseobjv# NUMBER NOT NULL,
  lvl1obj# NUMBER,
  lvl2obj# NUMBER,
  lvl0type# NUMBER NOT NULL,
  lvl1type# NUMBER,
  lvl2type# NUMBER,
  owner# NUMBER,
  ownername VARCHAR2(384 BYTE) NOT NULL,
  lvl0name VARCHAR2(384 BYTE) NOT NULL,
  lvl1name VARCHAR2(384 BYTE),
  lvl2name VARCHAR2(384 BYTE),
  intcols NUMBER NOT NULL,
  cols NUMBER,
  kernelcols NUMBER,
  tab_flags NUMBER,
  trigflag NUMBER,
  assoc# NUMBER,
  obj_flags NUMBER,
  ts# NUMBER,
  tsname VARCHAR2(90 BYTE),
  property NUMBER,
  start_scn NUMBER NOT NULL,
  drop_scn NUMBER,
  xidusn NUMBER,
  xidslt NUMBER,
  xidsqn NUMBER,
  flags NUMBER,
  logmnr_spare1 NUMBER,
  logmnr_spare2 NUMBER,
  logmnr_spare3 VARCHAR2(1000 BYTE),
  logmnr_spare4 DATE,
  logmnr_spare5 NUMBER,
  logmnr_spare6 NUMBER,
  logmnr_spare7 NUMBER,
  logmnr_spare8 NUMBER,
  logmnr_spare9 NUMBER,
  parttype NUMBER,
  subparttype NUMBER,
  unsupportedcols NUMBER,
  complextypecols NUMBER,
  ntparentobjnum NUMBER,
  ntparentobjversion NUMBER,
  ntparentintcolnum NUMBER,
  logmnrtloflags NUMBER,
  logmnrmcv VARCHAR2(30 BYTE),
  acdrflags NUMBER,
  acdrtsobj# NUMBER,
  acdrrowtsintcol# NUMBER,
  CONSTRAINT logmnrggc_gtlo_pk PRIMARY KEY (logmnr_uid,keyobj#,baseobjv#)
);