CREATE TABLE "SYSTEM".logmnr_attribute$ (
  version# NUMBER,
  "NAME" VARCHAR2(384 BYTE),
  attribute# NUMBER,
  attr_toid RAW(16),
  attr_version# NUMBER,
  synobj# NUMBER,
  properties NUMBER,
  charsetid NUMBER,
  charsetform NUMBER,
  "LENGTH" NUMBER,
  precision# NUMBER,
  "SCALE" NUMBER,
  externname VARCHAR2(4000 BYTE),
  xflags NUMBER,
  spare1 NUMBER,
  spare2 NUMBER,
  spare3 NUMBER,
  spare4 NUMBER,
  spare5 NUMBER,
  setter NUMBER,
  getter NUMBER,
  toid RAW(16) NOT NULL,
  logmnr_uid NUMBER(22),
  logmnr_flags NUMBER(22),
  CONSTRAINT logmnr_attribute$_pk PRIMARY KEY (logmnr_uid,toid,version#,attribute#) DISABLE NOVALIDATE
);