CREATE TABLE "SYSTEM".logstdby$parameters (
  "NAME" VARCHAR2(30 BYTE),
  "VALUE" VARCHAR2(2000 BYTE),
  "TYPE" NUMBER,
  "SCN" NUMBER,
  spare1 NUMBER,
  spare2 NUMBER,
  spare3 VARCHAR2(2000 BYTE)
);