CREATE TABLE "SYSTEM".redo_db (
  dbid NUMBER NOT NULL,
  global_dbname VARCHAR2(129 BYTE),
  dbuname VARCHAR2(32 BYTE),
  "VERSION" VARCHAR2(32 BYTE),
  thread# NUMBER NOT NULL,
  resetlogs_scn_bas NUMBER,
  resetlogs_scn_wrp NUMBER,
  resetlogs_time NUMBER NOT NULL,
  presetlogs_scn_bas NUMBER,
  presetlogs_scn_wrp NUMBER,
  presetlogs_time NUMBER NOT NULL,
  seqno_rcv_cur NUMBER,
  seqno_rcv_lo NUMBER,
  seqno_rcv_hi NUMBER,
  seqno_done_cur NUMBER,
  seqno_done_lo NUMBER,
  seqno_done_hi NUMBER,
  gap_seqno NUMBER,
  gap_ret NUMBER,
  gap_done NUMBER,
  apply_seqno NUMBER,
  apply_done NUMBER,
  purge_done NUMBER,
  has_child NUMBER,
  error1 NUMBER,
  status NUMBER,
  create_date DATE,
  ts1 NUMBER,
  ts2 NUMBER,
  gap_next_scn NUMBER,
  gap_next_time NUMBER,
  curscn_time NUMBER,
  resetlogs_scn NUMBER NOT NULL,
  presetlogs_scn NUMBER NOT NULL,
  gap_ret2 NUMBER,
  curlog NUMBER,
  endian NUMBER,
  enqidx NUMBER,
  spare4 NUMBER,
  spare5 DATE,
  spare6 VARCHAR2(65 BYTE),
  spare7 VARCHAR2(129 BYTE),
  ts3 NUMBER,
  curblkno NUMBER,
  spare8 NUMBER,
  spare9 NUMBER,
  spare10 NUMBER,
  spare11 NUMBER,
  spare12 NUMBER
);