CREATE TABLE "SYSTEM".redo_log (
  dbid NUMBER NOT NULL,
  global_dbname VARCHAR2(129 BYTE),
  dbuname VARCHAR2(32 BYTE),
  "VERSION" VARCHAR2(32 BYTE),
  thread# NUMBER NOT NULL,
  resetlogs_scn_bas NUMBER,
  resetlogs_scn_wrp NUMBER,
  resetlogs_time NUMBER NOT NULL,
  presetlogs_scn_bas NUMBER,
  presetlogs_scn_wrp NUMBER,
  presetlogs_time NUMBER NOT NULL,
  sequence# NUMBER NOT NULL,
  dupid NUMBER,
  status1 NUMBER,
  status2 NUMBER,
  create_time VARCHAR2(32 BYTE),
  close_time VARCHAR2(32 BYTE),
  done_time VARCHAR2(32 BYTE),
  first_scn_bas NUMBER,
  first_scn_wrp NUMBER,
  first_time NUMBER,
  next_scn_bas NUMBER,
  next_scn_wrp NUMBER,
  next_time NUMBER,
  first_scn NUMBER,
  next_scn NUMBER,
  resetlogs_scn NUMBER NOT NULL,
  "BLOCKS" NUMBER,
  block_size NUMBER,
  old_blocks NUMBER,
  create_date DATE,
  error1 NUMBER,
  error2 NUMBER,
  filename VARCHAR2(513 BYTE),
  ts1 NUMBER,
  ts2 NUMBER,
  endian NUMBER,
  spare2 NUMBER,
  spare3 NUMBER,
  spare4 NUMBER,
  spare5 DATE,
  spare6 VARCHAR2(65 BYTE),
  spare7 VARCHAR2(129 BYTE),
  ts3 NUMBER,
  presetlogs_scn NUMBER NOT NULL,
  spare8 NUMBER,
  spare9 NUMBER,
  spare10 NUMBER,
  old_status1 NUMBER,
  old_status2 NUMBER,
  old_filename VARCHAR2(513 BYTE)
);