CREATE TABLE "SYSTEM".rolling$status (
  revision NUMBER,
  phase NUMBER,
  batchid NUMBER,
  status NUMBER,
  coordid NUMBER,
  oprimary NUMBER,
  fprimary NUMBER,
  pid NUMBER,
  "INSTANCE" NUMBER,
  dbtotal NUMBER,
  dbactive NUMBER,
  "LOCATION" VARCHAR2(128 BYTE),
  init_time TIMESTAMP,
  build_time TIMESTAMP,
  start_time TIMESTAMP,
  switch_time TIMESTAMP,
  finish_time TIMESTAMP,
  last_instid NUMBER,
  last_batchid NUMBER,
  spare1 NUMBER,
  spare2 NUMBER,
  spare3 VARCHAR2(128 BYTE)
);