CREATE TABLE "SYSTEM".rolling$plan (
  instid NUMBER,
  batchid NUMBER,
  directid NUMBER,
  taskid NUMBER,
  revision NUMBER,
  phase NUMBER,
  status NUMBER,
  progress NUMBER,
  "SOURCE" NUMBER,
  target NUMBER,
  rflags NUMBER,
  "OPCODE" NUMBER,
  p1 VARCHAR2(256 BYTE),
  p2 VARCHAR2(256 BYTE),
  p3 VARCHAR2(256 BYTE),
  p4 VARCHAR2(256 BYTE),
  description VARCHAR2(256 BYTE),
  exec_status NUMBER,
  exec_info VARCHAR2(256 BYTE),
  exec_time TIMESTAMP,
  finish_time TIMESTAMP,
  post_status NUMBER,
  spare1 NUMBER,
  spare2 NUMBER,
  spare3 VARCHAR2(256 BYTE)
);