/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [Person].[Pet]
(
[PetID] [int] NOT NULL,
[Name] [nvarchar] (25) NULL,
[Color] [nvarchar] (15) NULL,
[Type] [nvarchar] (15) NULL,
[Breed] [nvarchar] (25) NULL,
[OwnerID] [int] NOT NULL
)
GO
ALTER TABLE [Person].[Pet] ADD CONSTRAINT [PK_Pet] PRIMARY KEY CLUSTERED ([PetID])
GO
ALTER TABLE [Person].[Pet] ADD CONSTRAINT [FK_Pet_OwnerID] FOREIGN KEY ([OwnerID]) REFERENCES [Person].[Person] ([BusinessEntityID])
GO
